# Generated by Django 5.1.5 on 2025-04-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('ALL', 'All'), ('PK', 'Pakistani'), ('CH', 'Chinese'), ('KO', 'Korean'), ('IT', 'Italian'), ('JA', 'Japanese')], max_length=50)),
                ('image', models.ImageField(upload_to='food_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
